# Imports
from pyscreeze import Box


# ============================================================================
#                           === CONFIGURATION FILE ===
# ============================================================================
# ----------------------------------------------------------------------------
#                           --- EXTRACT SETTINGS ---
#               Options for the extract part of the pipeline.
# ----------------------------------------------------------------------------
# Path to test XML file with raw offer data generated by Social Soul:
EXAMPLE_SOCIAL_SOUL_INPUT_XML_FILE_PATH = './rsc/xml/LomadeeDownload.xml'
#
#
# ----------------------------------------------------------------------------
#                           --- TRANSFORM SETTINGS ---
#               Options for the transform part of the pipeline.
# ----------------------------------------------------------------------------
# When refining a Social Soul offers dataframe, keep the following columns:
COLUMNS_OF_INTEREST_LIST = [
    'offerName',            # Offer name
    #'sellerId',
    #'sellerThumbnail',
    'offerLink',            # URL to offer
    'offerThumbnail',       # Picture of product in white background
    'priceFrom',            # Price before discount
    #'sellerName',
    'priceTo',              # Price after discount
    #'sku',
    #'categoryName',
    #'categoryId',
]
# 
# When creating a new offer image for IG, use this font:
DEFAULT_FONT_FILE_PATH = './rsc/fnt/open_sans.ttf'
# 
# When creating a new offer image for IG, use this story template:
DEFAULT_STORY_TEMPLATE_IMG_FILE_PATH = './rsc/img/tmpl_story_720x1280_final.png'
# 
# During execution, temporary image files will be stored in this folder:
PATH_TO_TMP_IMAGE_FOLDER = './tmp/img/'
# 
# During execution, temporary parquet files will be stored in this folder:
PATH_TO_TMP_PARQUET_FOLDER = './tmp/parquet/'
# 
# After transform, export offers dataframe as a parquet file with this name:
DEFAULT_LOAD_READY_PARQUET_FILE_NAME = 'offers_ig_ready'
# 
# ----------------------------------------------------------------------------
#                           --- LOAD SETTINGS ---
#               Options for the load (post) part of the pipeline.
# ----------------------------------------------------------------------------
# Before being used in IG story post, offer image will be temporarily stored 
# in Android device using this folder path and name:
PATH_TO_TMP_IMAGE_FOLDER_ANDROID = '/storage/emulated/0/DCIM/temp/'
DEFAULT_TMP_STORY_IMG_FILE_NAME_ANDROID = 'offer.png'
# 
# Visual elements for IG bot navigation are located in this folder:
PATH_TO_VE_DIR = './rsc/ve/'
PATH_TO_TMP_SS_DIR = './tmp/ss/'
# 
# When adding a link sticker to IG story post, use this display text:
DEFAULT_LINK_STICKER_TXT = 'ver oferta'
# 
# 
# ----------------------------------------------------------------------------
#                           --- CONSTANTS ---
#   Visual elements to be used by IG bot for navigation in the IG app.
# ----------------------------------------------------------------------------
#  
# Blue "new story" button in home screen
BTN_NEW_STORY = f'{PATH_TO_VE_DIR}00a_btn_newstory.png'
# 
# "Add to story" header in IG story gallery
HDR_ADD_TO_STORY = f'{PATH_TO_VE_DIR}01a_hdr_addtostory.png'
#
# Region of first image in IG story gallery
BOX_1ST_IMG_IN_STRY_GAL = Box(left=3, top=668, width=353, height=627)
# 
# "Add sticker" button in story build context
BTN_ADD_STICKER = f'{PATH_TO_VE_DIR}02a_btn_addsticker.png'
# 
# Search field in "Add Sticker" context
FLD_SEARCH_STICKER = f'{PATH_TO_VE_DIR}03a_fld_searchsticker.png'
# 
# Search field region in "Add Sticker" context
RGN_SEARCH_STICKER = f'{PATH_TO_VE_DIR}04a_rgn_search.png'
#
# Sticker link in "Add sticker" context
STCKR_LINK = f'{PATH_TO_VE_DIR}05a_stckr_link.png'
# 
# "URL" field in "Add sticker" context
FLD_STICKER_URL = f'{PATH_TO_VE_DIR}06a_txt_httpexample.png'
#
# "Customize sticker text" button in "Add sticker" context
BTN_CUSTOMIZE_STICKER_TEXT = f'{PATH_TO_VE_DIR}06b_btn_customstickertext.png'
#
# "Sticker text" region in "Add sticker" context
RGN_CUSTOMIZE_STICKER_TEXT = f'{PATH_TO_VE_DIR}07a_rgn_stickertext.png'
# 
# "Done" button in "Add sticker" context
BTN_DONE = f'{PATH_TO_VE_DIR}07b_btn_done.png'
#
# Blue link sticker icon 
ICO_LINK_STICKER_BLUE = f'{PATH_TO_VE_DIR}08a_ico_linksticker.png'
# 
# White link sticker icon
ICO_LINK_STICKER_WHITE = f'{PATH_TO_VE_DIR}09a_ico_linksticker.png'
# 
# Black link sticker icon
ICO_LINK_STICKER_BLACK = f'{PATH_TO_VE_DIR}10a_ico_linksticker.png'
# 
# Purple link sticker icon
ICO_LINK_STICKER_PURPLE = f'{PATH_TO_VE_DIR}11a_ico_linksticker.png'
# 
# Post to your story button
BTN_YOUR_STORY = f'{PATH_TO_VE_DIR}12a_btn_yourstory.png'
# 
# Post to close friends button
BTN_CLOSE_FRIENDS = f'{PATH_TO_VE_DIR}12b_btn_closefriends.png'